/************************************************************\
 **  Copyright (c) 2011-2021 Anlogic, Inc.
 **  All Right Reserved.
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	D:/014_FPGA_Project/EG4S20BG256_Lm35Prjv0.0.1/prj/eglm35/al_ip/lm35_adc.v
 ** Date	:	2019 11 21
 ** TD version	:	4.6.14314
\************************************************************/

`timescale 1ns / 1ps

module lm35_adcch1 ( eoc, dout, clk, pd, s, soc );
	output 		 eoc;
	output  		[11:0] dout;

	input  		clk;
	input  		pd;
	input  		[2:0] s;
	input  		soc;

	EG_PHY_ADC #(
		.CH1("ENABLE"))
		adc (
		.clk(clk),
		.pd(pd),
		.s(s),
		.soc(soc),
		.eoc(eoc),
		.dout(dout));

endmodule